### ISSUE TITLE
해당 오류가 지속적으로 발생합니다.

### ISSUE THREAD

**Issue by LIBIBKK** [qwerty1434/TOY_PROJECT#1]
오류 해결 완료입니다.

**Comment by LIBIBKK** [comment]
> C:\TOY_PROJECT-master\tools.py:31: RuntimeWarning: invalid value encountered in true_divide mfi = 100 - 100 / (1 + (np.array(positive_mf)/np.array(negative_mf)))
> 
> 해당 오류가 계속해서 발생하는데 무슨 이유일까요?

**Comment by LIBIBKK** [comment]
> C:\TOY_PROJECT-master\tools.py:31: RuntimeWarning: invalid value encountered in true_divide mfi = 100 - 100 / (1 + (np.array(positive_mf)/np.array(negative_mf)))
> 
> 해당 오류가 계속해서 발생하는데 무슨 이유일까요?

**Comment by qwerty1434** [comment]
invalid value encountered in true_divide오류는 0으로 값을 나누는 과정에서 발생한 문제로
0으로 나누는 부분을 수정했습니다. 오류 제안 감사합니다.
